"""Constants used by model download and verification workflows."""

from __future__ import annotations

DEFAULT_MODEL_DOWNLOAD_TIMEOUT_SEC = 60.0
DEFAULT_ARIA2_CONNECTIONS = 8
DEFAULT_ARIA2_SPLIT = 8
SHA256_CHUNK_SIZE = 1024 * 1024
MIN_DISK_RESERVE_BYTES = 50 * 1024 * 1024
DISK_RESERVE_RATIO_DIVISOR = 20
MODEL_DOWNLOADERS = {"auto", "httpx", "aria2"}

__all__ = [
    "DEFAULT_ARIA2_CONNECTIONS",
    "DEFAULT_ARIA2_SPLIT",
    "DEFAULT_MODEL_DOWNLOAD_TIMEOUT_SEC",
    "DISK_RESERVE_RATIO_DIVISOR",
    "MIN_DISK_RESERVE_BYTES",
    "MODEL_DOWNLOADERS",
    "SHA256_CHUNK_SIZE",
]
